### ISSUE TITLE
Docs for Anaconda Installation

### ISSUE THREAD

**Issue by afrubin** [kc-lab/dms2dfe#5]
The documentation http://kc-lab.github.io/kc-lab.github.io/dms2dfe/v1.0.6/html/1installation.html hard links to Anaconda v4.0.0, but newer versions are available. It would probably be better to link to the Anaconda installation or download page. Additionally, some users (especially those who only want to run `dms2dfe`) may want Miniconda instead.

I also think that the creation of a conda environment is sufficiently useful that it should be mentioned in the short installation instructions on the main page.

**Comment by rraadd88** [comment]
Thanks for both the suggestions.
I have replaced the Anaconda link to https://conda.io/docs/user-guide/install/download.html: . This would take the users directly to the Anaconda's user guides - where they can download latest versions of Anaconda/Miniconda.
  
Also the short installation instructions are updated to include recommended creation of anaconda environment.: http://kc-lab.github.io/dms2dfe/latest/html/index.html#basic-usage
